version: "3.3"
services:
  mongo:
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Yy3QCwj6mM7ADDhm
    image: mongo
    volumes:
      - ./data:/data/db
      - ./mongo-setup:/docker-entrypoint-initdb.d
    ports:
      - "27017"
    networks:
      - pinterest-net

  pinterest-server:
    build: ./
    ports:
      - 3000:3000
    networks:
      - pinterest-net

networks:
  pinterest-net:

